### ISSUE TITLE
Only getting index.js in build directory, no included files

### ISSUE THREAD

**Issue by jonestristand** [gjuchault/typescript-library-starter#113]
**Describe the bug**
When I build my library, both the ./build/cjs and ./build/esm contain only index.js and index.js.map. ./build/src has .d.ts files for all of my files however. When trying to use the library in another project it will fail, as all of the require and import paths do not exist in the build output.

**To Reproduce**
1. Create a project with more than one source file in it
2. Run `npm run build`
3. Look in the ./build output directory.

**Expected behavior**
All .ts files get compiled.

**Desktop (please complete the following information):**
 - OS: macOS
 - Node version: 16.4.2

**Comment by gjuchault** [comment]
Hey @jonestristand 
Nice catch. I was just missing a `bundle: true` configuration on esbuild. I just pushed the fix here: https://github.com/gjuchault/typescript-library-starter/commit/ff379fc1a57d0515236ccd63d0f0566a4d263e15 if you want to cherry-pick on your side :+1:
